
#' Harmonize publishers (ENB)
#'
#' This function harmonizes publishers in ENB
#' @param genres the data.table format work_by_row table
#' @keywords publishers
#' @export
#' @examples
#' harmonize_publishers()
#' see https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/ on installation
#' 
#' 

harmonize_publishers <- function(works){
  # Note:
  # the standardization was done with a focus on 1850-1930 and top 50 publishers
  # many remain unstandardized
  #checked the top 50 of them,
  #just look and plot and compare the top ones about this...
  #admit that ones with less than 10 haven't been checked...
  
  
  works <- data.table(works)
  works[,kirjastus_orig:=kirjastus]
  works[,kirjastus:=trimws(kirjastus)]
  works[kirjastus=="[s.n.],",kirjastus:=""]
  works[kirjastus=="[s.n.],",kirjastus:=""]
  works[kirjastus=="[s.n.,",kirjastus:=""]
  works[kirjastus=="s.n.,",kirjastus:=""]
  works[kirjastus=="s.n.],",kirjastus:=""]
  works[kirjastus=="s. n.,",kirjastus:=""]
  works[kirjastus=="s.n,",kirjastus:=""]
  works[kirjastus=="s.n.",kirjastus:=""]
  
  works[,kirjastus:=str_replace_all(kirjastus,",","")]
  works[,kirjastus:=str_replace_all(kirjastus,"-"," ")]
  works[,kirjastus:=trimws(kirjastus)]
  works[,kirjastus:=tolower(kirjastus)]
  works[,kirjastus:=str_replace_all(kirjastus,"\\. ",".")]
  works[,kirjastus:=str_replace_all(kirjastus,"'i rmtkpl. ","")]
  works[kirjastus=="3.diviisi staap",kirjastus:="3.diviis"]
  works[kirjastus=="a.busch'i rmtkpl.",kirjastus:="a.busch"]
  works[kirjastus=="a.ingelman",kirjastus:="a.ingelmann"]
  works[kirjastus=="b.pärli",kirjastus:="br.pärli"]
  works[kirjastus=="c.mathiesen",kirjastus:="k.mattiesen"]
  works[kirjastus=="draamastuudio teater",kirjastus:="draamateater"]
  works[kirjastus=="eesti draama studio",kirjastus:="draamateater"]
  works[kirjastus=="eesti draamastuudio",kirjastus:="draamateater"]
  works[kirjastus=="eesti draamateater",kirjastus:="draamateater"]
  works[kirjastus=="draamateaater",kirjastus:="draamateater"]
  works[kirjastus=="eesti karskuseseltside kestoimekond",kirjastus:="eesti karskusliit"]
  works[kirjastus=="eesti karskusseltside kesktoimekond",kirjastus:="eesti karskusliit"]
  works[kirjastus=="eesti kirjanduse seltsi kodu uurimise toimkond",kirjastus:="eesti kirjanduse selts"]
  works[kirjastus=="eesti kirjanduse seltsi koolikirjanduse toimkond",kirjastus:="eesti kirjanduse selts"]
  works[kirjastus=="eesti kirjanduse kirjastus",kirjastus:="eesti kirjandus"]
  works[kirjastus=="eesti kubermangu kooliõp.vastastikkuse abiandm.selts",kirjastus:="eesti kubermangu kooliõpetajate vastastikku abiandmise selts"]
  works[kirjastus=="eestimaa konsistooriumi kirj kassa",kirjastus:="eestimaa konsistooriumi kirjastuskassa"]
  works[kirjastus=="eestimaa kooliõpetajate vastast.abiandm.selts",kirjastus:="eestimaa kooliõpetajate selts"]
  works[kirjastus=="eestimaa kooliõpetajate vastastiku abiandmise seltsi raamatukauplus",kirjastus:="eestimaa kooliõpetajate selts"]
  works[kirjastus=="eestimaa kooliõpetajate selts",kirjastus:="eesti õpetajate liit"]
  #works[kirjastus=="eestimaa kooliõpetajate vastastiku abiandmise selts (k./ü.\\"\\"\\"\\"kool\\"\\"\\"\\")",kirjastus:="eestimaa kooliõpetajate selts"]
  works[kirjastus=="eesti nmkü liit",kirjastus:="eesti noorte meeste kristlike ühingute liit"]
  works[kirjastus=="eesti põllutöö kirjanduse ühendus",kirjastus:="eesti põllutöö ühendus"]
  works[kirjastus=="eesti töörahva kommuuna kultuura ja ariduse valitsus",kirjastus:="eesti töörahwa kommuuna kultuura ja ariduse walitsus"]
  works[kirjastus=="estoonia muusika osakond",kirjastus:="estonia muusika osakond"]
  works[kirjastus=="f.brandt",kirjastus:=""]
  works[kirjastus=="fr.kreutzwald",kirjastus:="f.r.kreutzwald"]
  works[kirjastus=="füüsika õpetamise komisjon",kirjastus:="füüsika õpetamiskomisjon"]
  works[kirjastus=="g.pihlaka raamatukauplus",kirjastus:="g.pihlakas"]
  works[kirjastus=="g.pihlaka ramatukauplus",kirjastus:="g.pihlakas"]
  works[kirjastus=="g.pihlaka rmtkpl.",kirjastus:="g.pihlakas"]
  works[kirjastus=="pihlakas'e kirjastus",kirjastus:="g.pihlakas"]
  works[kirjastus=="g.vänja",kirjastus:="g.wänja kuluga rosenberg"]
  works[kirjastus=="g.v.rosenberg",kirjastus:="g.wänja kuluga rosenberg"]
  works[kirjastus=="g.v.rosenberg?",kirjastus:="g.wänja kuluga rosenberg"]
  works[kirjastus=="g.vänjag.rosenberg",kirjastus:="g.wänja kuluga rosenberg"]
  works[kirjastus=="hariduse ja sotsiaalministeerium",kirjastus:="hariduse ja sotsiaalministeerium"]
  works[kirjastus=="hariduse ja sotsiaalministeeriumi koolivalitsus",kirjastus:="hariduse ja sotsiaalministeerium"]
  works[kirjastus=="haridus ja sotsiaalministeerium",kirjastus:="hariduse ja sotsiaalministeerium"]
  works[kirjastus=="haridus ja sotsiaalministeeriumi koolivalitsus",kirjastus:="hariduse ja sotsiaalministeerium"]
  works[kirjastus=="haridusministeeriumi kirjastus",kirjastus:="haridusministeerium"]
  works[kirjastus=="haridusministeeriumi koolivalitsus",kirjastus:="haridusministeerium"]
  works[kirjastus=="haridusministeeriumi kutseoskuse osakond",kirjastus:="haridusministeerium"]
  works[kirjastus=="h.laasi raamatukauplus",kirjastus:="h.laasi rmtkpl."]
  works[kirjastus=="h.leoke'se rmtkpl.",kirjastus:="h.leoke"]
  works[kirjastus=="h.treffneri gümnaasium",kirjastus:="hugo treffneri gümnaasium"]
  works[kirjastus=="internationali traktaati selts osakond tartus",kirjastus:="internatsionaali traktaadiselts"]
  works[kirjastus=="internatsionali traktadiselts",kirjastus:="internatsionaali traktaadiselts"]
  works[kirjastus=="dreimanni rmtkpl.",kirjastus:="j.dreimann"]
  works[kirjastus=="j.dreimanni rmtkpl",kirjastus:="j.dreimann"]
  works[kirjastus=="j.treimann",kirjastus:="j.dreimann"]
  works[kirjastus=="j.e.meigas ja j.kehlmann",kirjastus:="j.e.meigase rmtkpl"]
  works[kirjastus=="j.g.marquardt)",kirjastus:="j.g.marquardt"]
  works[kirjastus=="j.h.gressel)",kirjastus:="j.h.gressel"]
  works[kirjastus=="j.kalkun'i raamatukauplus",kirjastus:="j.kalkuni raamatukauplus"]
  works[kirjastus=="j.keerdo",kirjastus:="j.kerdo"]
  works[kirjastus=="j.kerdo :",kirjastus:="j.kerdo"]
  works[kirjastus=="j.lass",kirjastus:="joh.lass"]
  works[kirjastus=="joh.semmiste",kirjastus:="joh.semm"]
  works[kirjastus=="j.palmgren'i raamatukauplus",kirjastus:="j.palmgren"]
  works[kirjastus=="j.palmgreni rmtkpl",kirjastus:="j.palmgren"]
  works[kirjastus=="j.palmgreni rmtkpl.",kirjastus:="j.palmgren"]
  works[kirjastus=="j.ploompuu rmtkpl.",kirjastus:="j.ploompuu"]
  works[kirjastus=="j.ploompuu raamatukauplus",kirjastus:="j.ploompuu"]
  works[kirjastus=="ploompuu raamatukauplus",kirjastus:="j.ploompuu"]
  works[kirjastus=="ploompuu",kirjastus:="j.ploompuu"]
  works[kirjastus=="j.reimanni pealadu",kirjastus:="j.reimanni rmtkpl"]
  works[kirjastus=="reimanni raamatukauplus",kirjastus:="j.reimanni rmtkpl"]
  works[kirjastus=="j.r.rerzold",kirjastus:="j.r.rezold"]
  works[kirjastus=="j.tamman",kirjastus:="j.tammann"]
  works[kirjastus=="jummala sanna väljalautamisse sõbbrad",kirjastus:="jummala sanna wäljalautamisse söbbrad"]
  works[kirjastus=="jutuleht :",kirjastus:="jutuleht"]
  works[kirjastus=="kaitseliidu peastaap",kirjastus:="kaitseliit"]
  works[kirjastus=="kaitseväe ühendatud õppeasutiste staap",kirjastus:="kaitseväe ühendatud õppeasutised"]
  works[kirjastus=="kaitseväe ühendatud õppeasutused",kirjastus:="kaitseväe ühendatud õppeasutised"]
  works[kirjastus=="kaitseväe ühendatud õppeasutuste ohvitseride kogu",kirjastus:="kaitseväe ühendatud õppeasutised"]
  works[kirjastus=="kaitsevägede ühendatud õppeasutiste staap",kirjastus:="kaitseväe ühendatud õppeasutised"]
  works[kirjastus=="kaitsevägede staabi ii osakond",kirjastus:="kaitsevägede staap"]
  works[kirjastus=="kaitsevägede staabi vi osakond",kirjastus:="kaitsevägede staap"]
  works[kirjastus=="kaitsevägede staabi v osakond",kirjastus:="kaitsevägede staap"]
  works[kirjastus=="kaitsevägede ülemjuhataja",kirjastus:="kaitsevägede staap"]
  works[kirjastus=="k.busch'i raamatukauplus",kirjastus:="k.busch"]
  works[kirjastus=="k.busch'i rmtkpl.",kirjastus:="k.busch"]
  works[kirjastus=="k.buschi rmtkpl.",kirjastus:="k.busch"]
  works[kirjastus=="kili & co.",kirjastus:="kili & co"]
  works[kirjastus=="kili & ko",kirjastus:="kili & co"]
  works[kirjastus=="kindralstaabi 6.osakond",kirjastus:="kindralstaap"]
  works[kirjastus=="kindralstaabi ii osakond",kirjastus:="kindralstaap"]
  works[kirjastus=="kindralstaabi iv osakond",kirjastus:="kindralstaap"]
  works[kirjastus=="kindralstaabi vi osakond",kirjastus:="kindralstaap"]
  works[kirjastus=="k.laurmanni rmtkpl.",kirjastus:="k.laurmann"]
  works[kirjastus=="kluge ja ströhmi raamatukauplus",kirjastus:="kluge ja ströhm"]
  works[kirjastus=="c.mattiesen",kirjastus:="k.mattiesen"]
  works[kirjastus=="kristliku rahwakirjanduse agentur",kirjastus:="kristliku rahvakirjanduse agentur"]
  works[kirjastus=="kristlik 7 da päeva adventistide eesti ühisus",kirjastus:="kristlik seitsmenda päewa adwentistide eesti ühisus"]
  works[kirjastus=="k.sööt ja g.roht",kirjastus:="k.sööt"]
  works[kirjastus=="küõ õppejaoskond",kirjastus:="kaitseväe ühendatud õppeasutised"]
  works[kirjastus=="küõ sõjakool",kirjastus:="kaitseväe ühendatud õppeasutised"]
  works[kirjastus=="küõ sõjakooli patarei",kirjastus:="kaitseväe ühendatud õppeasutised"]
  works[kirjastus=="mattiesen",kirjastus:="k.mattiesen"]
  works[kirjastus=="merekindluste staap",kirjastus:="merejõudude staap"]
  works[kirjastus=="merelaevastiku divisjoni staap",kirjastus:="merejõudude staap"]
  works[kirjastus=="merijõudude staap",kirjastus:="merejõudude staap"]
  works[kirjastus=="naiskodukaitse keskjuhatus",kirjastus:="naiskodukaitse"]
  works[kirjastus=="n.erna ;",kirjastus:="n.erna"]
  works[kirjastus=="noorte kotkaste päästaap",kirjastus:="noorte kotkaste peastaap"]
  works[kirjastus=="odamees carl sarap",kirjastus:="odamees"]
  works[kirjastus=="paltimaa õigeusus vennaste selts ja riia peetri pauluse vennasteselts",kirjastus:="paltimaa õigeusu vennaste selts"]
  works[kirjastus=="paltimaa õigeusu vennaste selts ja riia peetri pauluse vennaste selts",kirjastus:="paltimaa õigeusu vennaste selts"]
  works[kirjastus=="paltimaa õigeusu vennasteselts ja riia peetri pauluse vennaste selts",kirjastus:="paltimaa õigeusu vennaste selts"]
  works[kirjastus=="pärnu maakonnavalitsuse haridusosakond",kirjastus:="pärnu maakonna koolivalitsus"]
  works[kirjastus=="p.erna raamatukauplus",kirjastus:="p.erna"]
  works[kirjastus=="p.erna rmtkpl",kirjastus:="p.erna"]
  works[kirjastus=="p.erna rmtkpl.",kirjastus:="p.erna"]
  works[kirjastus=="postimehe rmtkpl",kirjastus:="postimees"]
  works[kirjastus=="postitalitus",kirjastus:="postivalitsus"]
  works[kirjastus=="posti telegraafi telefoni valitsus",kirjastus:="postivalitsus"]
  works[kirjastus=="r.krupp.",kirjastus:="r.krupp"]
  works[kirjastus=="r.põder'i rmtkpl",kirjastus:="r.põder"]
  works[kirjastus=="r.põderi rmtkpl.",kirjastus:="r.põder"]
  works[kirjastus=="schnackenburg",kirjastus:="schnakenburg"]
  works[kirjastus=="schnakenburg :",kirjastus:="schnakenburg"]
  works[kirjastus=="seiler",kirjastus:="seileri mootoritehas"]
  works[kirjastus=="s n.",kirjastus:=""]
  works[kirjastus=="s.n",kirjastus:=""]
  works[trimws(kirjastus)=="s.n.",kirjastus:=""]
  works[str_detect(kirjastus,"^s.n."),kirjastus:=""]
  works[str_detect(kirjastus,"s.n"),kirjastus:=""]
  works[str_detect(kirjastus,"^sõjav"),kirjastus:="sõjavägi"]
  works[str_detect(kirjastus,"^sõjamini"),kirjastus:="sõjaministeerium"]
  works[str_detect(kirjastus,"siuru"),kirjastus:="siuru"]
  works[kirjastus=="spadv eesti liit",kirjastus:="spadv kog.eesti liit"]
  works[kirjastus=="spadvk eesti liit",kirjastus:="spadv kog.eesti liit"]
  works[kirjastus=="spadwk eesti liit",kirjastus:="spadv kog.eesti liit"]
  works[kirjastus=="tallinna eesti kirjastuse ühisus ;",kirjastus:="tallinna eesti kirjastuse ühisus"]
  works[kirjastus=="tallinna eesti kirjastus ühisus",kirjastus:="tallinna eesti kirjastuse ühisus"]
  works[kirjastus=="tallinna kubermangu karskuse kuratoorium",kirjastus:="tallinna kubermangu karskuse kuratorium"]
  works[kirjastus=="tallinna kubermangu karskuse kuratoriumi väljaanne",kirjastus:="tallinna kubermangu karskuse kuratorium"]
  works[kirjastus=="tallinna kub.karskuse kuratorium",kirjastus:="tallinna kubermangu karskuse kuratorium"]
  works[kirjastus=="t.m.franzdorfi raamatukauplus",kirjastus:="t.m.franzdorf"]
  works[kirjastus=="t.mutsu teatrikirjastus",kirjastus:="t.mutsu"]
  works[kirjastus=="vanemuine",kirjastus:="vanemuise näitelava"]
  works[kirjastus=="vanemuise näielava",kirjastus:="vanemuise näitelava"]
  works[kirjastus=="vanemuise näitelava.",kirjastus:="vanemuise näitelava"]
  works[kirjastus=="vanemuise teater",kirjastus:="vanemuise näitelava"]
  works[kirjastus=="wanemuise näitelava",kirjastus:="vanemuise näitelava"]
  works[kirjastus=="wanemuise näitelawa",kirjastus:="vanemuise näitelava"]
  works[kirjastus=="tarto wannemuine selts",kirjastus:="vanemuise näitelava"]
  works[kirjastus=="võru õpetajateseminar",kirjastus:="võru õpetajate seminar"]
  works[kirjastus=="võru seminar",kirjastus:="võru õpetajate seminar"]
  works[kirjastus=="w.bormi pär.",kirjastus:="w.borm"]
  works[kirjastus=="f.w.borm",kirjastus:="w.borm"]
  works[str_detect(kirjastus,"noor eesti"),kirjastus:="noor eesti"]
  works[str_detect(kirjastus,"mutsu"),kirjastus:="t.mutsu"]
  works[str_detect(kirjastus,"ploompuu"),kirjastus:="j.ploompuu"]
  works[str_detect(kirjastus,"postimehe"),kirjastus:="postimees"]
  works[str_detect(kirjastus,"postimees"),kirjastus:="postimees"]
  works[str_detect(kirjastus,"h\\.laakmann"),kirjastus:="h.laakmann"]
  works[str_detect(kirjastus,"eesti kirjastus"),kirjastus:="eesti kirjastuse ühisus"]
  works[kirjastus=="eesti kirjanduseselts",kirjastus:="eesti kirjanduse selts"]
  works[kirjastus=="hermann",kirjastus:="k.a.hermann"]
  works[kirjastus=="hermann'i raamatukauplus",kirjastus:="k.a.hermann"]
  works[kirjastus=="pealadu hermanni rmtkpl.",kirjastus:="k.a.hermann"]
  works[kirjastus=="hermanni raamatukauplus",kirjastus:="k.a.hermann"]
  works[kirjastus=="hermann'i rmtkpl.",kirjastus:="k.a.hermann"]
  works[kirjastus=="pealadu hermanni kaupluses",kirjastus:="k.a.hermann"]
  works[kirjastus=="leoke'se kirjastus",kirjastus:="h.leoke"]
  works[kirjastus=="leoke",kirjastus:="h.leoke"]
  works[kirjastus=="leoke'se raamatuäri antikvariaat",kirjastus:="h.leoke"]
  works[str_detect(kirjastus,"h\\.leoke"),kirjastus:="h.leoke"]
  works[str_detect(kirjastus,"a\\.busch"),kirjastus:="a.busch"]
  works[str_detect(kirjastus,"jummala"),kirjastus:="jummala sanna wäljalautamisse söbbrad"]
  works[kirjastus=="eesti karskuseseltside kesktoimekond",kirjastus:="eesti karskusliit"]
  works[kirjastus=="eesti karskusseltside kesktoimkond",kirjastus:="eesti karskusliit"]
  works[kirjastus=="briti ja väljamaa piibliselts",kirjastus:="briti ja välismaa piibliselts"]
  works[kirjastus=="briti ja väljamaa piibliselts",kirjastus:="briti ja välismaa piibliselts"]
  works[kirjastus=="briti ja väljamaa piibliselts",kirjastus:="briti ja välismaa piibliselts"]
  works[kirjastus=="briti ja väljamaa piibliselts",kirjastus:="briti ja välismaa piibliselts"]
  works[kirjastus=="briti ja väljamaa piibliselts",kirjastus:="briti ja välismaa piibliselts"]
  works[str_detect(kirjastus,"Lindfors"),kirjastus:="Lindfors,"]
  works[str_detect(kirjastus,"\\["),kirjastus:=str_replace_all(kirjastus,"\\[","")]
  works[str_detect(kirjastus,"\\]"),kirjastus:=str_replace_all(kirjastus,"\\]","")]
  works[kirjastus=="",kirjastus:=NA]
  
  works[,kirjastus_first:=min(aeg,na.rm = T),by=kirjastus]
  works[is.na(kirjastus),kirjastus_first:=NA]
  
  
}
